name: idle_pirate_workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - pkgs/idle_pirate
  - pkgs/mini_audio
  - pkgs/pirate_speak


hooks:
  user_defines:
    pirate_speak:
      languages: [en, pirate_en, es, pirate_es, nl, pirate_nl]


