name: idle_pirate_workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - pkgs/idle_pirate
  - pkgs/mini_audio

hooks:
  user_defines:
    pirate_speak:
      translations: [en, pirate_en, es, pirate_es, nl, pirate_nl, de, pirate_de]

