name: idle_pirate

description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.13.0-25.0.dev

dependencies:
  flutter:
    sdk: flutter

  mini_audio:
    path: ../mini_audio

  pirate_speak:
    path: ../pirate_speak

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks: ^1.0.3
  data_assets: ^0.19.6
  meta: ^1.11.0
  record_use: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/pirate_logo.jpg"
  ios: true
  macos:
    generate: true
    image_path: "assets/images/pirate_logo.jpg"

flutter:
  uses-material-design: true
