name: pirate_speak
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0-78.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  record_use: ^0.6.0
  data_assets: ^0.19.6
  hooks: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
